export const data = {
    nfts: [
        {
            image: "/images/nfts/8.png",
            className: "md:mt-20",
            title: "The Dead Fella",
            name: "Lori Hart",
            price: "0.04 SOL",
            time: "1h 20m 11s",
            avatar: "/images/avatars/0.png",
        },
        {
            image: "/images/nfts/9.png",
            className: "md:mt-10",
            title: "Emperor's Guard",
            name: "Claude Banks",
            price: "0.10 SOL",
            time: "2h 32m 0",
            avatar: "/images/avatars/1.png",
        },
        {
            image: "/images/nfts/0.png",
            className: "md:mt-20",
            title: "Snow Bunny",
            name: "Noel G",
            price: "0.34 SOL",
            time: "1h 29m 9s",
            avatar: "/images/avatars/2.png",
        },
    ],
    collection: [
        {
            image: "/images/nfts/1.png",
            title: "The Dead Fella",
            name: "Lori Hart",
            price: "0.04 SOL",
            time: "1h 20m 11s",
            avatar: "/images/avatars/0.png",
        },
        {
            image: "/images/nfts/2.png",
            title: "Crypto Ape",
            name: "Jack Miles",
            price: "1.2 SOL",
            time: "2h 15m 30s",
            avatar: "/images/avatars/1.png",
        },
        {
            image: "/images/nfts/3.png",
            title: "Pixel Punk",
            name: "Maria Clark",
            price: "0.8 SOL",
            time: "3h 10m 20s",
            avatar: "/images/avatars/2.png",
        },
        {
            image: "/images/nfts/4.png",
            title: "Galaxy Gangster",
            name: "Tom Lee",
            price: "2.5 SOL",
            time: "4h 45m 50s",
            avatar: "/images/avatars/3.png",
        },
        {
            image: "/images/nfts/5.png",
            title: "Moon Walker",
            name: "Sarah Green",
            price: "1.75 SOL",
            time: "5h 5m 40s",
            avatar: "/images/avatars/4.png",
        },
        {
            image: "/images/nfts/6.png",
            title: "Cyber Kitty",
            name: "Anna Brown",
            price: "0.95 SOL",
            time: "6h 30m 25s",
            avatar: "/images/avatars/5.png",
        },
        {
            image: "/images/nfts/7.png",
            title: "Neo Samurai",
            name: "Jake Wilson",
            price: "3.1 SOL",
            time: "7h 40m 15s",
            avatar: "/images/avatars/6.png",
        },
        {
            image: "/images/nfts/8.png",
            title: "Golden Skull",
            name: "Eve Davis",
            price: "4.25 SOL",
            time: "8h 20m 50s",
            avatar: "/images/avatars/7.png",
        },
        {
            image: "/images/nfts/9.png",
            title: "Ethereal Warrior",
            name: "Chris Taylor",
            price: "2.9 SOL",
            time: "9h 55m 10s",
            avatar: "/images/avatars/8.png",
        },
        {
            image: "/images/nfts/10.png",
            title: "Choen Kepa",
            name: "Port Deak",
            price: "0.29 SOL",
            time: "6h 55m 10s",
            avatar: "/images/avatars/9.png",
        },
    ],
    creators: [
        {
            name: "Luna Star",
            balance: "123 SOL",
            avatar: "/images/avatars/1.png",
        },
        {
            name: "Aria Bloom",
            balance: "234 SOL",
            avatar: "/images/avatars/2.png",
        },
        {
            name: "Nova Skye",
            balance: "345 SOL",
            avatar: "/images/avatars/3.png",
        },
        {
            name: "Leo Vale",
            balance: "456 SOL",
            avatar: "/images/avatars/4.png",
        },
        {
            name: "Ivy Ray",
            balance: "567 SOL",
            avatar: "/images/avatars/5.png",
        },
        {
            name: "Ezra Dawn",
            balance: "678 SOL",
            avatar: "/images/avatars/6.png",
        },
        {
            name: "Kai Frost",
            balance: "789 SOL",
            avatar: "/images/avatars/7.png",
        },
        {
            name: "Mila Solis",
            balance: "890 SOL",
            avatar: "/images/avatars/8.png",
        },
        {
            name: "Orion Peak",
            balance: "901 SOL",
            avatar: "/images/avatars/9.png",
        },
        {
            name: "Zara Quinn",
            balance: "1012 SOL",
            avatar: "/images/avatars/10.png",
        },
    ],
};
